- best_score: null
  detailed_scores:
    accuracy: 0.8137931034482758
    f1_score: 0.8123608192164801
    precision: 0.8116774222528337
    recall: 0.8137931034482758
    roc_auc: 0.7868421052631579
  model: lr
  parameters:
    C: 1.0
    class_weight: null
    dual: false
    fit_intercept: true
    intercept_scaling: 1
    l1_ratio: 0.0
    max_iter: 100
    n_jobs: null
    penalty: deprecated
    random_state: null
    solver: lbfgs
    tol: 0.0001
    verbose: 0
    warm_start: false
  score: 0.8137931034482758
  training_time: 0.07909965515136719
- best_score: null
  detailed_scores:
    accuracy: 0.8068965517241379
    f1_score: 0.7978049279054045
    precision: 0.8067243136841364
    recall: 0.8068965517241379
    roc_auc: 0.7531578947368421
  model: rf
  parameters:
    bootstrap: true
    ccp_alpha: 0.0
    class_weight: null
    criterion: gini
    max_depth: null
    max_features: sqrt
    max_leaf_nodes: null
    max_samples: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    monotonic_cst: null
    n_estimators: 100
    n_jobs: null
    oob_score: false
    random_state: null
    verbose: 0
    warm_start: false
  score: 0.8068965517241379
  training_time: 0.5010199546813965
- best_score: null
  detailed_scores:
    accuracy: 0.7586206896551724
    f1_score: 0.7591770671320005
    precision: 0.7598075180182124
    recall: 0.7586206896551724
    roc_auc: 0.7352631578947368
  model: svm
  parameters:
    C: 1.0
    break_ties: false
    cache_size: 200
    class_weight: null
    coef0: 0.0
    decision_function_shape: ovr
    degree: 3
    gamma: scale
    kernel: rbf
    max_iter: -1
    probability: false
    random_state: null
    shrinking: true
    tol: 0.001
    verbose: false
  score: 0.7586206896551724
  training_time: 0.5147035121917725
- best_score: null
  detailed_scores:
    accuracy: 0.7931034482758621
    f1_score: 0.7882876743446459
    precision: 0.788830965931736
    recall: 0.7931034482758621
    roc_auc: 0.7521052631578948
  model: dt
  parameters:
    ccp_alpha: 0.0
    class_weight: null
    criterion: gini
    max_depth: null
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    monotonic_cst: null
    random_state: null
    splitter: best
  score: 0.7931034482758621
  training_time: 0.05769538879394531
- best_score: null
  detailed_scores:
    accuracy: 0.4206896551724138
    f1_score: 0.35266457680250785
    precision: 0.6431308155446086
    recall: 0.4206896551724138
    roc_auc: 0.5389473684210526
  model: nb
  parameters:
    priors: null
    var_smoothing: 1.0e-09
  score: 0.4206896551724138
  training_time: 0.046353816986083984
- best_score: null
  detailed_scores:
    accuracy: 0.7931034482758621
    f1_score: 0.789667150792819
    precision: 0.7891927123746857
    recall: 0.7931034482758621
    roc_auc: 0.756842105263158
  model: gb
  parameters:
    ccp_alpha: 0.0
    criterion: friedman_mse
    init: null
    learning_rate: 0.1
    loss: log_loss
    max_depth: 3
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    n_estimators: 100
    n_iter_no_change: null
    random_state: null
    subsample: 1.0
    tol: 0.0001
    validation_fraction: 0.1
    verbose: 0
    warm_start: false
  score: 0.7931034482758621
  training_time: 0.8906018733978271
- best_score: null
  detailed_scores:
    accuracy: 0.7655172413793103
    f1_score: 0.7643458245367113
    precision: 0.7634790851996681
    recall: 0.7655172413793103
    roc_auc: 0.7357894736842105
  model: knn
  parameters:
    algorithm: auto
    leaf_size: 30
    metric: minkowski
    metric_params: null
    n_jobs: null
    n_neighbors: 5
    p: 2
    weights: uniform
  score: 0.7655172413793103
  training_time: 7.850458383560181
